RoomMonitor/Models/Room.cs
using System;

namespace RoomMonitor.Models
{
    public class Room
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int DefaultStartMinutes { get; set; }

        public int CurrentStartMinutes { get; set; }

        public int StartMinutes => CurrentStartMinutes == 0 ? DefaultStartMinutes : CurrentStartMinutes;

        public DateTime? CurrentEndDateTime { get; set; }

        public DateTime? CurrentPauseTime { get; set; }

        public bool TimerIsGoing { get; set; }
    }
}

RoomMonitor/Models/RoomMonitorContext.cs
using System.Data.Entity;

namespace RoomMonitor.Models
{
    public class RoomMonitorContext : DbContext
    {
        public DbSet<Room> Rooms { get; set; }
    }
}

RoomMonitor/Models/RoomViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace RoomMonitor.Models
{
    public class RoomViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int StartMinutes { get; set; }

        public List<SelectListItem> AudioFiles { get; set; }

        public List<SelectListItem> ImageFiles { get; set; }
    }
}

RoomMonitor/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using RoomMonitor.Models;

namespace RoomMonitor.Controllers
{
    public class AdministrationController : Controller
    {
        // GET: Administration
        public ActionResult Index()
        {
            var model = new List<RoomViewModel>();

            using (var db = new RoomMonitorContext())
            {
                var rooms = db.Rooms.ToList();
                model.AddRange(rooms.Select(room => new RoomViewModel
                {
                    Id = room.Id,
                    Name = room.Name,
                    StartMinutes = room.DefaultStartMinutes,
                    AudioFiles = GetAudioList(),
                    ImageFiles = GetImageList()
                }));
            }
            return View(model);
        }

        private List<SelectListItem> GetAudioList()
        {
            var relativeAudioPath = "~/Content/Audio/";
            var audioPath = Server.MapPath(Url.Content(relativeAudioPath));
            var audiofileTypeExtensions = new List<string>
            {
                ".wav",
                ".mp3"
            };
            return Directory.GetFiles(audioPath, "*.*").Where(x =>
            {
                var extension = Path.GetExtension(x);
                return extension != null && audiofileTypeExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase);
            }).Select(file => new SelectListItem
            {
                Text = Path.GetFileName(file),
                Value = new Uri(Request.Url, Url.Content(relativeAudioPath + Path.GetFileName(file))).AbsoluteUri
            }).ToList();
        }


        private List<SelectListItem> GetImageList()
        {
            var relativeImagePath = "~/Content/Images/";
            var imagePath = Server.MapPath(Url.Content(relativeImagePath));
            var imageFileTypeExtensions = new List<string>
            {
                ".jpeg",
                ".gif",
                ".bmp",
                ".png",
                ".jpg"
            };
            return Directory.GetFiles(imagePath, "*.*").Where(x =>
            {
                var extension = Path.GetExtension(x);
                return extension != null && imageFileTypeExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase);
            }).Select(file => new SelectListItem
            {
                Text = Path.GetFileName(file),
                Value = new Uri(Request.Url, Url.Content(relativeImagePath + Path.GetFileName(file))).AbsoluteUri
            }).ToList();
        }}
}

RoomMonitor/Controllers/RoomController.cs
using System.Web.Mvc;
using RoomMonitor.Models;

namespace RoomMonitor.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        public ActionResult Index(int id)
        {
            var model = new RoomViewModel();
            using (var db = new RoomMonitorContext())
            {
                var room = db.Rooms.Find(id);
                model.Id = id;
                model.Name = room.Name;
                model.StartMinutes = room.DefaultStartMinutes;
            }
            return View(model);
        }
    }
}

RoomMonitor/Controllers/RoomManagementController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using RoomMonitor.Models;

namespace RoomMonitor.Controllers
{
    public class RoomManagementController : Controller
    {
        private RoomMonitorContext db = new RoomMonitorContext();

        // GET: RoomManagement
        public ActionResult Index()
        {
            return View(db.Rooms.ToList());
        }

        // GET: RoomManagement/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // GET: RoomManagement/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoomManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,DefaultStartMinutes")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Rooms.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room);
        }

        // GET: RoomManagement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: RoomManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,DefaultStartMinutes")] Room room)
        {
            if (ModelState.IsValid)
            {
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(room);
        }

        // GET: RoomManagement/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Room room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        // POST: RoomManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Rooms.Find(id);
            db.Rooms.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoomMonitor/Views/Administration/Index.cshtml
@model IEnumerable<RoomMonitor.Models.RoomViewModel>
<div class="container-fluid">
    @foreach (var room in Model)
    {
        <div class="room">
            @Html.Partial("_RoomEdit", room)
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript">
        $(function() {
            var roomHub = $.connection.roomHub;
            roomHub.client.initiateAdminTimer = function(roomId, startMinutes) {
                setTimeInMinutes(roomId, startMinutes);
            }
            roomHub.client.startAdminTimer = function(roomId, endDateTime) {
                endDateTime = new Date(Date.parse(endDateTime));
                startTimer(roomId, endDateTime);
            };
            roomHub.client.pauseAdminTimer = function(roomId) {
                pauseTimer(roomId);
            };
            roomHub.connection.start()
                .done(function() {
                    $('.initiateButton')
                        .click(function(event) {
                            var roomId = $(event.target).data('roomid');
                            var startMinutes = $('input[Name="StartMinutes"][data-roomid="' + roomId + '"]').val();
                            roomHub.server.initiateTimer(roomId, startMinutes);
                        });
                    $('.startPauseButton')
                        .click(function(event) {
                            var roomId = $(event.target).data('roomid');
                            var isGoing = $(event.target).data('going');
                            if (isGoing) {
                                $(event.target).text("Start");
                                $(event.target).data('going', false);
                                roomHub.server.pauseTimer(roomId);
                            } else {
                                $(event.target).text("Pause");
                                $(event.target).data('going', true);
                                roomHub.server.startTimer(roomId);
                            }
                        });
                    $('.showTextClue')
                        .click(function(event) {
                            var roomId = $(event.target).data('roomid');
                            var isGoing = $(event.target).data('going');
                            if (isGoing) {
                                $(event.target).text("Show Clue");
                                $(event.target).data('going', false);
                                roomHub.server.hideTextClue(roomId);
                            } else {
                                $(event.target).text("Hide Clue");
                                $(event.target).data('going', true);
                                var clueText = $('textarea[name="TextClue"][data-roomid="' + roomId + '"]').val();
                                roomHub.server.showTextClue(roomId, clueText);
                            }
                        });
                    $('.playAudio')
                        .click(function(event) {
                            var roomId = $(event.target).data('roomid');
                            var audio = $('select[name="audioFile"][data-roomid="' + roomId + '"] option:selected')
                                .val();
                            roomHub.server.playAudio(roomId, audio);
                        });
                    $('.showImage')
                        .click(function(event) {
                            var roomId = $(event.target).data('roomid');
                            var isGoing = $(event.target).data('going');
                            if (isGoing) {
                                $(event.target).text("Show Image");
                                $(event.target).data('going', false);
                                roomHub.server.hideImage(roomId);
                            } else {
                                $(event.target).text("Hide Image");
                                $(event.target).data('going', true);
                                var image = $('select[name="imageFile"][data-roomid="' + roomId + '"] option:selected')
                                    .val();
                                roomHub.server.showImage(roomId, image);
                            }
                        });
                    startInterval();
                });

            function setTimeInMinutes(roomId, totalMinutes) {
                var hours = Math.floor(totalMinutes / 60);
                var minutes = totalMinutes % 60;
                setTime(roomId, hours, minutes, 0, 0);
            }

            var timeInterval;
            var rooms = {};

            function startInterval() {
                for (var roomId = 1; roomId <= @Model.Count(); roomId++) {
                    rooms[roomId] = {};
                }
                if (timeInterval) clearInterval(timeInterval);
                timeInterval = setInterval(function() {
                    setAllTimers();
                });
            }

            function setAllTimers() {
                for (var roomId = 1; roomId <= @Model.Count(); roomId++) {
                    var room = rooms[roomId];
                    if (room.timerPaused === false && room.currentEndDate) {
                        if (Date.parse(room.currentEndDate) - Date.parse(new Date()) <= 0) {
                            room.timerFinished = true;
                            setTimeFinished(roomId);
                        } else {
                            setRemainingTime(roomId, room.currentEndDate);
                        }

                    }
                }
            }

            function startTimer(roomId, endDateTime) {
                rooms[roomId].timerPaused = false;
                rooms[roomId].currentEndDate = endDateTime;
            }

            function pauseTimer(roomId) {
                rooms[roomId].timerPaused = true;
            }

            function setRemainingTime(roomId, endDateTime) {
                var millisecondsRemaining = endDateTime - new Date();
                var hours = Math.floor(millisecondsRemaining / 1000 / 60 / 60);
                var minutes = Math.floor((millisecondsRemaining / 1000 / 60) % 60);
                var seconds = Math.floor((millisecondsRemaining / 1000) % 60);
                var milliseconds = millisecondsRemaining % 1000;
                setTime(roomId, hours, minutes, seconds, milliseconds);
            }

            function setTime(roomId, hours, minutes, seconds, milliseconds) {
                $('.admin-timer[data-roomid="' + roomId + '"] .hours').text(pad(hours,2));
                $('.admin-timer[data-roomid="' + roomId + '"] .minutes').text(pad(minutes,2));
                $('.admin-timer[data-roomid="' + roomId + '"] .seconds').text(pad(seconds, 2));
                $('.admin-timer[data-roomid="' + roomId + '"] .milliseconds').text(pad(milliseconds,3));
            }

            function setTimeFinished(roomId) {
                setTime(roomId, 0, 0, 0, 0);
                rooms[roomId].currentEndDate = false;
            }

            function pad(n, width, z) {
                z = z || '0';
                n = n + '';
                return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;
            }

        });
    </script>
}

RoomMonitor/Views/Administration/_RoomEdit.cshtml
@model RoomMonitor.Models.RoomViewModel
<div class="row">
    <div class="col-md-4">
        <h3>@Model.Name</h3>
    </div>
    <div class="col-md-4">
        <br />
        @Html.ActionLink(Model.Name + " Countdown", "Index", "Room", new {id = Model.Id}, null)
    </div>
    <div class="col-md-4">
        <br/>
        <div class="admin-timer" data-roomid="@Model.Id">
            <span class="hours"></span>:<span class="minutes"></span>:<span class="seconds"></span>:<span class="milliseconds"></span>
        </div>
    </div>
</div> 
<div class="row">
    <div class="col-md-4">
        @Html.LabelFor(m => m.StartMinutes, "Start Minutes")
        @Html.EditorFor(m => m.StartMinutes, new { htmlAttributes = new { data_roomId = Model.Id, @class = "form-control" } })
    </div>
    <div class="col-md-2">
        <br/>
        <button class="btn initiateButton" data-roomid="@Model.Id">Reset</button>
        <button class="btn startPauseButton" data-roomid="@Model.Id" data-going="false">Start</button>
    </div>
    <div class="col-md-4">
        @Html.Label("Text Clue")
        @Html.TextArea("TextClue", new {data_roomId = Model.Id, @class="form-control"})
    </div>
    <div class="col-md-1">
        <br/>
        <button class="btn showTextClue dr" data-roomid="@Model.Id" data-going="false">Show Clue</button>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        @Html.Label("Audio")
        @Html.DropDownList("audioFile", Model.AudioFiles, "Select", new {data_roomId = Model.Id, @class = "form-control" })
        
    </div>
    <div class="col-md-2">
        <br/>
        <button class="btn playAudio" data-roomid="@Model.Id">Play Audio</button>
    </div>
    <div class="col-md-4">
        @Html.Label("Image")
        @Html.DropDownList("imageFile", Model.ImageFiles, "Select", new {data_roomId = Model.Id, @class = "form-control" })
    </div>
    <div class="col-md-2">
        <br />
        <button class="btn showImage" data-roomid="@Model.Id" data-going="false">Show Image</button>
    </div>

</div>

RoomMonitor/Views/Room/Index.cshtml
@model RoomMonitor.Models.RoomViewModel
@{
    Layout = null;
    ViewData["Title"] = Model.Name;
}
<link rel="stylesheet" type="text/css" href="~/Content/timer.css" />
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="clue"></div>
            <div class="timer">
                <span class="hours"></span>:<span class="minutes"></span>:<span class="seconds"></span>:<span class="milliseconds"></span>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
<script src="~/signalr/hubs"></script>
<script>
    $(function () {
        var roomHub = $.connection.roomHub;
        roomHub.client.initiateTimer = function (startMinutes) {
            if (flashTimeInterval) clearInterval(flashTimeInterval);
            $('.timer').removeClass('hidden');
            setTimeInMinutes(startMinutes);
        };
        roomHub.client.startTimer = function (endDateTime) {
            if (flashTimeInterval) clearInterval(flashTimeInterval);
            $('.timer').removeClass('hidden');
            endDateTime = new Date(Date.parse(endDateTime));
            startTimer(endDateTime);
        };
        roomHub.client.pauseTimer = function () {
            if (flashTimeInterval) clearInterval(flashTimeInterval);
            $('.timer').removeClass('hidden');
            pauseTimer();
        };
        roomHub.client.showTextClue = function (text) {
            $('.timer').addClass('shrunk');
            $('.clue').text(text);
            $('.clue').addClass('shown');
        };
        roomHub.client.hideTextClue = function () {
            $('.clue').removeClass('shown');
            $('.timer').removeClass('shrunk');
            setTimeout(function() { $('.clue').text(''); }, 1000);
        };
        roomHub.client.playAudio = function(audioPath) {
            new Audio(audioPath).play();
        };
        roomHub.client.showImage = function(imagePath) {
            $('.timer').addClass('shrunk');
            $('.clue').prepend($('<img>', { id: 'imageClue', src:imagePath}));
            $('.clue').addClass('shown');
        };
        roomHub.client.hideImage = function() {
            $('.clue').removeClass('shown');
            $('.timer').removeClass('shrunk');
            setTimeout(function() {
                $('#imageClue').remove();
            }, 1000);
        };
        $.connection.hub.qs = 'id=' + @Model.Id;
        roomHub.connection.start(function() {
            console.log('connection started!');
            roomHub.server.updateRoom(@Model.Id);
        });
        setTimeInMinutes(@Model.StartMinutes);
    });

    function setTimeInMinutes(totalMinutes) {
        var hours = Math.floor(totalMinutes / 60);
        var minutes = totalMinutes % 60;
        setTime(hours, minutes, 0, 0);
    }

    var timeInterval;

    function startTimer(endDateTime) {
        if (flashTimeInterval) clearInterval(flashTimeInterval);
        if (timeInterval) clearInterval(timeInterval);
        timeInterval = setInterval(function() {
            setRemainingTime(endDateTime);
            if (Date.parse(endDateTime) - Date.parse(new Date()) <= 0) {
                endTime();
                clearInterval(timeInterval);
            }
        });
    }

    function pauseTimer() {
        if (timeInterval) clearInterval(timeInterval);
    }

    function setRemainingTime(endDateTime) {
        var millisecondsRemaining = endDateTime - new Date();
        var hours = Math.floor(millisecondsRemaining / 1000 / 60 / 60);
        var minutes = Math.floor((millisecondsRemaining / 1000 / 60) % 60);
        var seconds = Math.floor((millisecondsRemaining / 1000) % 60);
        var milliseconds = millisecondsRemaining % 1000;
        setTime(hours, minutes, seconds, milliseconds);
    }

    function setTime(hours, minutes, seconds, milliseconds) {
        $('.hours').text(pad(hours,2));
        $('.minutes').text(pad(minutes,2));
        $('.seconds').text(pad(seconds, 2));
        $('.milliseconds').text(pad(milliseconds,3));
    }

    var flashTimeInterval;

    function endTime() {
        setTime(0, 0, 0, 0);
        if (flashTimeInterval) clearInterval(flashTimeInterval);
        flashTimeInterval = setInterval(function() {
            if ($('.timer').hasClass('hidden')) {
                $('.timer').removeClass('hidden');
            } else {
                $('.timer').addClass('hidden');
            }
        },
            500);
        $.connection.roomHub.server.timerFinished(@Model.Id);
    }

    function pad(n, width, z) {
        z = z || '0';
        n = n + '';
        return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n;
    }
</script>

RoomMonitor/Views/RoomManagement/Create.cshtml
@model RoomMonitor.Models.Room

@using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Room</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DefaultStartMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DefaultStartMinutes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DefaultStartMinutes, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

RoomMonitor/Views/RoomManagement/Delete.cshtml
@model RoomMonitor.Models.Room

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Room @Model.Id</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DefaultStartMinutes)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DefaultStartMinutes)
            </dd>
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

RoomMonitor/Views/RoomManagement/Details.cshtml
@model RoomMonitor.Models.Room

    <div>
        <h4>Room @Model.Id</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DefaultStartMinutes)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DefaultStartMinutes)
            </dd>
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

RoomMonitor/Views/RoomManagement/Edit.cshtml
@model RoomMonitor.Models.Room

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Room @Model.Id</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DefaultStartMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DefaultStartMinutes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DefaultStartMinutes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

RoomMonitor/Views/RoomManagement/Index.cshtml
@model IEnumerable<RoomMonitor.Models.Room>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultStartMinutes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrentEndDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimerIsGoing)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefaultStartMinutes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentEndDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimerIsGoing)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>

RoomMonitor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Monitor - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Room Monitor", "Index", "Administration", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Administration", "Index", "Administration")</li>
                    <li>@Html.ActionLink("Room Management", "Index", "RoomManagement")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Puzzle Theory Room Monitor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>